---
- name: Testing andrewrothstein.credhub
  hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Executing 'credhub --version'
      ansible.builtin.command: credhub --version
      changed_when: false
      register: credhub_test_output
    - name: Output of 'credhub --version'
      ansible.builtin.debug:
        msg: '{{ credhub_test_output.stdout }}'
