---
- name: Installing andrewrothstein.unarchivedeps
  ansible.builtin.include_role:
    name: andrewrothstein.unarchivedeps
- name: Resolve platform specific vars
  ansible.builtin.include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: Checking for install at {{ credhub_exe }}
  become: true
  ansible.builtin.stat:
    path: '{{ credhub_exe }}'
  changed_when: false
  register: credhub_binary
- name: Downloading and installing credhub
  when: not credhub_binary.stat.exists
  block:
    - name: Downloading {{ credhub_url }} to {{ credhub_tmp_tgz }}
      become: true
      become_user: root
      ansible.builtin.get_url:
        url: '{{ credhub_url }}'
        dest: '{{ credhub_tmp_tgz }}'
        checksum: '{{ credhub_checksum }}'
        mode: '644'
    - name: Mkdir {{ credhub_install_dir }}
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ credhub_install_dir }}'
        state: directory
        mode: '755'
    - name: Unarchiving {{ credhub_tmp_tgz }} to {{ credhub_install_dir }}
      become: true
      become_user: root
      ansible.builtin.unarchive:
        remote_src: true
        src: '{{ credhub_tmp_tgz }}'
        dest: '{{ credhub_install_dir }}'
        creates: '{{ credhub_exe }}'
  always:
    - name: Rm -f {{ credhub_tmp_tgz }}
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ credhub_tmp_tgz }}'
        state: absent
- name: Linking {{ credhub_link }} to {{ credhub_exe }}
  become: true
  become_user: root
  ansible.builtin.file:
    src: '{{ credhub_exe }}'
    dest: '{{ credhub_link }}'
    state: link
